# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}
    main: .

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: llm-cli
    homepage: https://github.com/fabriqaai/llm-cli
    repository:
      owner: fabriqaai
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    description: "CLI wrapper for Claude and Gemini CLIs"
    license: MIT
    commit_author:
      name: github-actions
      email: github-actions@github.com
    install: |
      bin.install "llm-cli"
    test: |
      system "#{bin}/llm-cli", "version"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'

release:
  github:
    owner: fabriqaai
    name: llm-cli
  mode: replace
