# goreleaser configuration for llm-cli
# Docs: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: llm-cli
    binary: llm-cli
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - name: llm-cli
    repository:
      owner: fabriqaai
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/fabriqaai/llm-cli"
    description: "A unified CLI for Claude and Gemini LLMs"
    license: "MIT"
    install: |
      bin.install "llm-cli"
    test: |
      system "#{bin}/llm-cli", "version"

release:
  github:
    owner: fabriqaai
    name: llm-cli
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
